<script>
    var lang = {
        "Some thing went wrong!": "{{ __('agent.Some thing went wrong!') }}",
        "OK": "{{ __('agent.OK') }}",
        "Cancel": "{{ __('agent.Cancel') }}",
        "Failed": "{{ __('agent.Failed') }}",
        "Success": "{{ __('agent.Success') }}",
        "Alert": "{{ __('agent.Alert') }}",
        "Password must me at least 8 characters!": "{{ __('admin.Password must me at least 8 characters!') }}",
        "New Password and Confirm Password not match!": "{{ __('admin.New Password and Confirm Password not match!') }}",
        "Please select a type and try again": "{{ __('agent.Please select a type and try again') }}",
        "Select type": "{{ __('agent.Select type') }}",
        "Select town": "{{ __('agent.Select town') }}",
        "Please select a town and try again": "{{ __('agent.Please select a town and try again') }}",
        "Select city": "{{ __('agent.Select city') }}",
        "Please select a city and try again": "{{ __('agent.Please select a city and try again') }}",
        "Select district": "{{ __('agent.Select district') }}",
        "Please select a property type": "{{ __('agent.Please select a property type') }}",
        "Please select a town": "{{ __('agent.Please select a town') }}",
        "Please select a city": "{{ __('agent.Please select a city') }}",
        "Please select a district": "{{ __('agent.Please select a district') }}",
        "Select Image": "{{ __('agent.Select Image') }}",
        "Please select an image and try again": "{{ __('agent.Please select an image and try again') }}",
        "Are you sure to update the status of this property?": "{{ __('agent.Are you sure to update the status of this property?') }}",
        "Are you sure to delete this property?": "{{ __('agent.Are you sure to delete this property?') }}",
        "Please select a package!": "{{ __('agent.Please select a package!') }}",
        "Please enter your first name!": "{{ __('agent.Please enter your first name!') }}",
        "Please enter your last name!": "{{ __('agent.Please enter your last name!') }}",
        "Please enter email address for invoice!": "{{ __('agent.Please enter email address for invoice!') }}",
        "Please enter company name!": "{{ __('agent.Please enter company name!') }}",
        "Please enter tax number": "{{ __('agent.Please enter tax number') }}",
        "Please change the price" : "{{ __('agent.Please change the price') }}",
        "Price required" : "{{ __('agent.Price required') }}",

        "Please select type of apartment": "{{ __('agent.Please select type of apartment') }}",
        "Please select apartment condition": "{{ __('agent.Please select apartment condition') }}",
        "Please enter apartment Gross m²": "{{ __('agent.Please enter apartment Gross m²') }}",
        "Please enter apartment Net m²": "{{ __('agent.Please enter apartment Net m²') }}",
        "Please select apartment Bedrooms": "{{ __('agent.Please select apartment Bedrooms') }}",
        "Please select apartment Livingrooms": "{{ __('agent.Please select apartment Livingrooms') }}",
        "Please select apartment Bathrooms": "{{ __('agent.Please select apartment Bathrooms') }}",
        "Please select apartment Status": "{{ __('agent.Please select apartment Status') }}",
        "Please select apartment Building Floors": "{{ __('agent.Please select apartment Building Floors') }}",
        "Please select apartment age": "{{ __('agent.Please select apartment age') }}",
        "Please select apartment heating type": "{{ __('agent.Please select apartment heating type') }}",
        "Please select apartment elevator": "{{ __('agent.Please select apartment elevator') }}",
        "Please select apartment floor": "{{ __('agent.Please select apartment floor') }}",

        "Please select type of villa": "{{ __('agent.Please select type of villa') }}",
        "Please select villa condition": "{{ __('agent.Please select villa condition') }}",
        "Please enter villa Gross m²": "{{ __('agent.Please enter villa Gross m²') }}",
        "Please enter villa m² net": "{{ __('agent.Please enter villa m² net') }}",
        "Please select villa Bedrooms": "{{ __('agent.Please select villa Bedrooms') }}",
        "Please select villa Livingrooms": "{{ __('agent.Please select villa Livingrooms') }}",
        "Please select villa Bathrooms": "{{ __('agent.Please select villa Bathrooms') }}",
        "Please enter villa Land m²": "{{ __('agent.Please enter villa Land m²') }}",
        "Please select villa age": "{{ __('agent.Please select villa age') }}",
        "Please select villa garden": "{{ __('agent.Please select villa garden') }}",
        "Please select villa floor": "{{ __('agent.Please select villa floor') }}",
        "Please select villa Elevator": "{{ __('agent.Please select villa Elevator') }}",

        "Please select type of house": "{{ __('agent.Please select type of house') }}",
        "Please select house condition": "{{ __('agent.Please select house condition') }}",
        "Please enter house Gross m²": "{{ __('agent.Please enter house Gross m²') }}",
        "Please enter house Net m²": "{{ __('agent.Please enter house Net m²') }}",
        "Please enter house Land m²": "{{ __('agent.Please enter house Land m²') }}",
        "Please select house Bedrooms": "{{ __('agent.Please select house Bedrooms') }}",
        "Please select house Livingrooms": "{{ __('agent.Please select house Livingrooms') }}",
        "Please select house Bathrooms": "{{ __('agent.Please select house Bathrooms') }}",
        "Please select house age": "{{ __('agent.Please select house age') }}",
        "Please select house garden": "{{ __('agent.Please select house garden') }}",
        "Please select house floor": "{{ __('agent.Please select house floor') }}",

        "Please select building condition": "{{ __('agent.Please select building condition') }}",
        "Please enter building Gross m²": "{{ __('agent.Please enter building Gross m²') }}",
        "Please select Shops in Building": "{{ __('agent.Please select Shops in Building') }}",
        "Please select Storage Rooms in Building": "{{ __('agent.Please select Storage Rooms in Building') }}",
        "Please select building age": "{{ __('agent.Please select building age') }}",
        "Please select Flats in Building": "{{ __('agent.Please select Flats in Building') }}",
        "Please select building elevator": "{{ __('agent.Please select building elevator') }}",
        "Please select building floor": "{{ __('agent.Please select building floor') }}",


        "Please select land type": "{{ __('agent.Please select land type') }}",
        "Please select land status": "{{ __('agent.Please select land status') }}",
        "Please enter land m2": "{{ __('agent.Please enter land m2') }}",
        "Alert": "{{ __('agent.Alert') }}",
        "Alert": "{{ __('agent.Alert') }}",
        "Alert": "{{ __('agent.Alert') }}",
        "Alert": "{{ __('agent.Alert') }}",
        "Alert": "{{ __('agent.Alert') }}",
        "Alert": "{{ __('agent.Alert') }}",
        "Alert": "{{ __('agent.Alert') }}",
    };
</script>
