<script>
    var lang = {
        "Are you sure to delete this agent?": "{{ __('admin.Are you sure to delete this agent?') }}",
        "All properties of this agent are also deleted!": "{{ __('admin.All properties of this agent are also deleted!') }}",
        "OK": "{{ __('admin.OK') }}",
        "Cancel": "{{ __('admin.Cancel') }}",
        "Failed": "{{ __('admin.Failed') }}",
        "Success": "{{ __('admin.Success') }}",
        "Alert": "{{ __('admin.Alert') }}",
        "Are you sure to update the status of this agent?": "{{ __('admin.Are you sure to update the status of this agent?') }}",
        "Are you sure to approve the profile of this agent?": "{{ __('admin.Are you sure to approve the profile of this agent?') }}",
        "Password must me at least 8 characters!": "{{ __('admin.Password must me at least 8 characters!') }}",
        "New Password and Confirm Password not match!": "{{ __('admin.New Password and Confirm Password not match!') }}",
        "Are you sure to delete this Broker Office?": "{{ __('admin.Are you sure to delete this Broker Office?') }}",
        "You are not be able to revert this.": "{{ __('admin.You are not be able to revert this.') }}",
        "Are you sure to update the status of this Broker Office?": "{{ __('admin.Are you sure to update the status of this Broker Office?') }}",
        "Are you sure to delete this Property Type?": "{{ __('admin.Are you sure to delete this Property Type?') }}",
        "Are you sure to update the status of this Property Type?": "{{ __('admin.Are you sure to update the status of this Property Type?') }}",
        "Are you sure to update the status of this property?": "{{ __('admin.Are you sure to update the status of this property?') }}",
        "Are you sure to delete this property?": "{{ __('admin.Are you sure to delete this property?') }}",
        "Are you sure to delete this Location?": "{{ __('admin.Are you sure to delete this Location?') }}",
        "Are you sure to update the status of this Location?": "{{ __('admin.Are you sure to update the status of this Location?') }}",
        "Are you sure to delete this Category?": "{{ __('admin.Are you sure to delete this Category?') }}",
        "Are you sure to update the status of this Category?": "{{ __('admin.Are you sure to update the status of this Category?') }}",
        "Are you sure to delete this Feature?": "{{ __('admin.Are you sure to delete this Feature?') }}",
        "Are you sure to update the status of this Feature?": "{{ __('admin.Are you sure to update the status of this Feature?') }}",
        "Are you sure to delete this Town?": "{{ __('admin.Are you sure to delete this Town?') }}",
        "Are you sure to update the status of this Town?": "{{ __('admin.Are you sure to update the status of this Town?') }}",
        "Something went wrong, please try again!": "{{ __('admin.Something went wrong, please try again!') }}",
        "Are you sure to delete this City?": "{{ __('admin.Are you sure to delete this City?') }}",
        "Are you sure to update the status of this City?": "{{ __('admin.Are you sure to update the status of this City?') }}",
        "Are you sure to delete this District?": "{{ __('admin.Are you sure to delete this District?') }}",
        "Are you sure to update the status of this District?": "{{ __('admin.Are you sure to update the status of this District?') }}",
        "All the properties which use this input are also deleted, Are you sure to delete?": "{{ __('admin.All the properties which use this input are also deleted, Are you sure to delete?') }}",
        "Are you sure to delete this Currency?": "{{ __('admin.Are you sure to delete this Currency?') }}",
        "Are you sure to update the status of this Currency?": "{{ __('admin.Are you sure to update the status of this Currency?') }}",
        "Are you sure to update the rate of this Currency?": "{{ __('admin.Are you sure to update the rate of this Currency?') }}",
        "Are you sure to delete this Message?": "{{ __('admin.Are you sure to delete this Message?') }}",
        "Are you sure to delete this subscriber?": "{{ __('admin.Are you sure to delete this subscriber?') }}",
        "Are you sure to delete this Package?": "{{ __('admin.Are you sure to delete this Package?') }}",
        "Are you sure to update the status of this Package?": "{{ __('admin.Are you sure to update the status of this Package?') }}",
        "Are you sure to delete this Discount?": "{{ __('admin.Are you sure to delete this Discount?') }}",
        "Are you sure to update the status of this Discount?": "{{ __('admin.Are you sure to update the status of this Discount?') }}",
        "Cancel": "{{ __('admin.Cancel') }}",


    };
</script>
